##############################################
# Default configuration for ML infrastructure
##############################################

# Paths configuration
paths:
  data_dir: 'data'
  models_dir: 'models'
  logs_dir: 'logs'
  
# API configuration
api:
  host: '0.0.0.0'
  port: 5000
  debug: false
  upload_folder: '/tmp/ml_uploads'
  
# Logging configuration
logging:
  level: 'INFO'
  log_to_console: true
  log_to_file: true
  log_filename: 'ml_infra.log'
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Model default parameters
model_defaults:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    subsample: 0.8
    
  neural_network:
    hidden_layers: [64, 32]
    activation: 'relu'
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    
# Preprocessing defaults
preprocessing:
  handle_missing: true
  scaling: 'standard'  # 'standard', 'minmax', or null
  categorical_encoding: 'onehot'  # 'onehot', 'label', or 'target'
  
# Cross-validation defaults
cross_validation:
  n_splits: 5
  shuffle: true
  
# Pipeline defaults
pipeline:
  data_pipeline:
    steps:
      - 'load_data'
      - 'preprocess'
      - 'split_data'
      
  training_pipeline:
    steps:
      - 'initialize_model'
      - 'train_model'
      - 'evaluate_model'
      - 'save_model'

# Security configuration
security:
  encryption:
    key_directory: 'secrets'
    load_keys_from_env: false
    
  # Model weights secure storage configuration
  secure_weights:
    enabled: true
    storage:
      primary: 's3'  # 's3', 'gcs', 'azure', or 'local'
      replicate_to: ['gcs']  # List of additional storage providers for replication
      s3_bucket: 'llm-models'
      gcs_bucket: 'llm-models'
      azure_container: 'llm-models'
      local_path: 'secure_weights'
      versioning_enabled: true
      checksum_algorithm: 'sha256'
      access_control_enabled: true
      encryption_enabled: true
    
    cache:
      enabled: true
      directory: 'weights_cache'
      max_size_gb: 10
      
# Secret management configuration
secrets:
  vault:
    enabled: false
    address: 'http://vault:8200'
    auth_method: 'kubernetes'
    
  model_weights:
    storage_type: 's3'  # 's3', 'gcs', 'azure', or 'local'
    s3_bucket: 'llm-models'
    gcs_bucket: 'llm-models'
    azure_container: 'llm-models'
    sync_enabled: true
    versioning_enabled: true
    cache_enabled: true
    cache_directory: 'weights_cache'
    cache_max_size_gb: 10
    access_control_enabled: true
    encryption_enabled: true
    checksum_algorithm: 'sha256'
    
  rotation:
    enabled: true
    schedule: '0 0 * * 0'  # Weekly on Sunday at midnight (cron format)

# LLM model configuration
llm:
  model_type: 'llama'
  weights:
    storage_type: 's3'
    local_weights_path: 'models/llm'
    use_secure_storage: true
    
  serving:
    quantization: '4bit'
    max_batch_size: 8
    max_sequence_length: 2048
    default_temperature: 0.7